name: Test ARC Runner

on:
  push:
    branches:
      - main

jobs:
  arc-test:
    runs-on: self-hosted
    steps:
      - name: Say Hello
        run: echo "👋 Hello Mrinal from my ARC runner on Minikube!"
